const product = [
  {
    id: 1,
    name: "Paracetamol 650mg",
    brand: "Cipla",
    category: "Medicines",
    price: 89,
    oldPrice: 120,
    rating: 4.8,
    reviews: 248,
    image: "/Public/Paracetamol.png",
    inStock: true,
    prescriptionRequired: false,
    featured: true,
  },
  {
    id: 2,
    name: "Vitamin C Tablets",
    brand: "Himalaya",
    category: "Supplements",
    price: 299,
    oldPrice: 349,
    rating: 4.9,
    reviews: 180,
    image: "/Public/vitaminC.png",
    inStock: true,
    prescriptionRequired: false,
    featured: true,
  },
  {
    id: 3,
    name: "Digital Thermometer",
    brand: "Dr. Morepen",
    category: "Medical Devices",
    price: 499,
    oldPrice: 599,
    rating: 4.7,
    reviews: 95,
    image: "/Public/thermometer.png",
    inStock: true,
    prescriptionRequired: false,
    featured: true,
  },
  {
    id: 4,
    name: "Hand Sanitizer 500ml",
    brand: "Dettol",
    category: "Personal Care",
    price: 149,
    oldPrice: 199,
    rating: 4.6,
    reviews: 134,
    image: "/Public/sanitizer.png",
    inStock: true,
    prescriptionRequired: false,
    featured: true,
  },
  {
    id: 5,
    name: "Blood Pressure Monitor",
    brand: "Omron",
    category: "Medical Devices",
    price: 1999,
    oldPrice: 2299,
    rating: 4.9,
    reviews: 312,
    image: "/Public/BP-thermometer.png",
    inStock: true,
    prescriptionRequired: false,
    featured: true,
  },
];

export default product;